
// src/components/community/SaveToTreasuryForm.tsx
'use client';
import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useUser } from '@/firebase';
import { useToast } from '@/hooks/use-toast';
import { saveSvgAsset } from '@/app/actions';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { LoaderCircle, Save, Download } from 'lucide-react';
import { type ColorPixel } from '@/lib/types';

type Creation = {
    id: string;
    creatorId: string;
    creatorName: string;
    creatorAvatarUrl: string;
    prompt: string;
    status: 'in-workshop' | 'published';
    createdAt: { seconds: number; nanoseconds: number; };
    pixels: ColorPixel[];
};

const SaveAssetSchema = z.object({
    assetName: z.string().min(2, 'Asset name must be at least 2 characters.'),
    value: z.coerce.number().min(0, 'Value must be a positive number.'),
});

const convertPixelsToObj = (pixels: ColorPixel[]): string => {
    let objContent = '# 3D Point Cloud generated by the Pleasance Community Gallery\n';

    const hexToRgb = (hex: string) => {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        if (!result) return '1 1 1'; // Default to white if parse fails
        const r = parseInt(result[1], 16) / 255;
        const g = parseInt(result[2], 16) / 255;
        const b = parseInt(result[3], 16) / 255;
        return `${r.toFixed(4)} ${g.toFixed(4)} ${b.toFixed(4)}`;
    };

    for (const pixel of pixels) {
        // OBJ format: v x y z r g b
        objContent += `v ${pixel.x.toFixed(4)} ${pixel.y.toFixed(4)} ${pixel.z.toFixed(4)} ${hexToRgb(pixel.color)}\n`;
    }

    return objContent;
};

export function SaveToTreasuryForm({ creation }: { creation: Creation }) {
    const { user } = useUser();
    const { toast } = useToast();
    const [isSaving, setIsSaving] = useState(false);

    const form = useForm<z.infer<typeof SaveAssetSchema>>({
        resolver: zodResolver(SaveAssetSchema),
        defaultValues: { assetName: creation.prompt || '', value: 10 },
    });

    useEffect(() => {
        form.setValue('assetName', creation.prompt);
    }, [creation.prompt, form]);

    async function onSubmit(data: z.infer<typeof SaveAssetSchema>) {
        if (!user) {
            toast({ variant: 'destructive', title: 'You must be logged in to save an asset.' });
            return;
        }
        setIsSaving(true);
        try {
            const result = await saveSvgAsset({
                userId: user.uid,
                assetName: data.assetName,
                value: data.value,
                pixels: creation.pixels,
            });

            if (result.error) {
                throw new Error(result.error);
            }
            toast({
                title: 'Asset Saved!',
                description: `"${data.assetName}" has been added to your Treasury.`,
            });
            form.reset();
        } catch (e) {
            const message = e instanceof Error ? e.message : 'An unknown error occurred.';
            toast({ variant: 'destructive', title: 'Failed to Save Asset', description: message });
        } finally {
            setIsSaving(false);
        }
    }
    
     const handleDownloadObj = () => {
        const objData = convertPixelsToObj(creation.pixels);
        const blob = new Blob([objData], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const fileName = creation.prompt.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'creation';
        a.download = `${fileName}.obj`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast({ title: 'Downloading .obj file...' });
    };

    if (!user) return null;

    return (
        <Card className="mt-4 bg-muted/50">
            <CardHeader>
                <CardTitle className="text-lg">Export & Save</CardTitle>
                <CardDescription>Download for fabrication or save this creation to your Treasury.</CardDescription>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                    <Button onClick={handleDownloadObj} variant="secondary" className="w-full">
                        <Download className="mr-2 h-4 w-4" />
                        Download .obj File for Fabrication
                    </Button>
                    <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 pt-4 border-t">
                        <FormField
                            control={form.control}
                            name="assetName"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Creation Name</FormLabel>
                                    <FormControl>
                                        <Input placeholder="e.g., 'Digital Sunrise'" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="value"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Creation Value (satoshis)</FormLabel>
                                    <FormControl>
                                        <Input type="number" placeholder="10000" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <Button type="submit" disabled={isSaving}>
                            {isSaving ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                            Save Creation to Treasury
                        </Button>
                    </form>
                </div>
            </CardContent>
        </Card>
    );
}
