
// src/app/workshop/page.tsx
'use client';

import { useState, useEffect, useMemo } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { LoaderCircle, Sparkles, Save, GalleryHorizontal, LogIn, Download } from 'lucide-react';
import { generateSvg3d as generateSvg3dAction, saveSvgAsset } from '@/app/actions';
import { GenerateSvg3dInputSchema, type ColorPixel } from '@/lib/types';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Svg3dCube } from '@/components/icons/svg3d-cube';
import { useToast } from '@/hooks/use-toast';
import { useUser } from '@/firebase';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { firestore } from '@/firebase/config';
import { doc, collection, query, orderBy } from 'firebase/firestore';
import { useCollectionData } from 'react-firebase-hooks/firestore';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import Link from 'next/link';
import { formatDistanceToNow } from 'date-fns';
import Image from 'next/image';

// Schemas and Types
const Svg3dSchema = GenerateSvg3dInputSchema;

const SaveAssetSchema = z.object({
    assetName: z.string().min(2, 'Asset name must be at least 2 characters.'),
    value: z.coerce.number().min(0, 'Value must be a positive number.'),
});

type Creation = {
    id: string;
    creatorId: string;
    creatorName: string;
    creatorAvatarUrl: string;
    prompt: string;
    createdAt: { seconds: number; nanoseconds: number; };
    pixels: ColorPixel[];
};


const convertPixelsToObj = (pixels: ColorPixel[]): string => {
    let objContent = '# 3D Point Cloud generated by the Pleasance Community Gallery\n';

    const hexToRgb = (hex: string) => {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        if (!result) return '1 1 1'; // Default to white if parse fails
        const r = parseInt(result[1], 16) / 255;
        const g = parseInt(result[2], 16) / 255;
        const b = parseInt(result[3], 16) / 255;
        return `${r.toFixed(4)} ${g.toFixed(4)} ${b.toFixed(4)}`;
    };

    for (const pixel of pixels) {
        // OBJ format: v x y z r g b
        objContent += `v ${pixel.x.toFixed(4)} ${pixel.y.toFixed(4)} ${pixel.z.toFixed(4)} ${hexToRgb(pixel.color)}\n`;
    }

    return objContent;
};


function SaveToTreasuryForm({ creation }: { creation: Creation }) {
    const { user } = useUser();
    const { toast } = useToast();
    const [isSaving, setIsSaving] = useState(false);

    const form = useForm<z.infer<typeof SaveAssetSchema>>({
        resolver: zodResolver(SaveAssetSchema),
        defaultValues: { assetName: creation.prompt || '', value: 10 },
    });

    useEffect(() => {
        form.setValue('assetName', creation.prompt);
    }, [creation.prompt, form]);

    async function onSubmit(data: z.infer<typeof SaveAssetSchema>) {
        if (!user) {
            toast({ variant: 'destructive', title: 'You must be logged in to save an asset.' });
            return;
        }
        setIsSaving(true);
        try {
            const result = await saveSvgAsset({
                userId: user.uid,
                assetName: data.assetName,
                value: data.value,
                pixels: creation.pixels,
            });

            if (result.error) {
                throw new Error(result.error);
            }
            toast({
                title: 'Asset Saved!',
                description: `"${data.assetName}" has been added to your Treasury.`,
            });
            form.reset();
        } catch (e) {
            const message = e instanceof Error ? e.message : 'An unknown error occurred.';
            toast({ variant: 'destructive', title: 'Failed to Save Asset', description: message });
        } finally {
            setIsSaving(false);
        }
    }
    
     const handleDownloadObj = () => {
        const objData = convertPixelsToObj(creation.pixels);
        const blob = new Blob([objData], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const fileName = creation.prompt.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'creation';
        a.download = `${fileName}.obj`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast({ title: 'Downloading .obj file...' });
    };

    if (!user) return null;

    return (
        <Card className="mt-4 bg-muted/50">
            <CardHeader>
                <CardTitle className="text-lg">Export & Save</CardTitle>
                <CardDescription>Download for fabrication or save this creation to your Treasury.</CardDescription>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                    <Button onClick={handleDownloadObj} variant="secondary" className="w-full">
                        <Download className="mr-2 h-4 w-4" />
                        Download .obj File for Fabrication
                    </Button>
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 pt-4 border-t">
                            <FormField
                                control={form.control}
                                name="assetName"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Creation Name</FormLabel>
                                        <FormControl>
                                            <Input placeholder="e.g., 'Digital Sunrise'" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="value"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Creation Value (USD)</FormLabel>
                                        <FormControl>
                                            <Input type="number" placeholder="100.00" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />
                            <Button type="submit" disabled={isSaving}>
                                {isSaving ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                                Save Creation to Treasury
                            </Button>
                        </form>
                    </Form>
                </div>
            </CardContent>
        </Card>
    );
}

export default function WorkshopPage() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeCreation, setActiveCreation] = useState<Creation | null>(null);
  const router = useRouter();
  const { user } = useUser();
  const { toast } = useToast();

  const creationsQuery = useMemo(() => query(collection(firestore, 'creations'), orderBy('createdAt', 'desc')), []);
  const [creations, isCreationsLoading, creationsError] = useCollectionData<Creation>(creationsQuery, {
      idField: 'id'
  });
  
  useEffect(() => {
    if (!activeCreation && creations && creations.length > 0) {
        setActiveCreation(creations[0]);
    }
  }, [creations, activeCreation]);

  const form = useForm<z.infer<typeof Svg3dSchema>>({
    resolver: zodResolver(Svg3dSchema),
    defaultValues: {
      prompt: '',
      cubeSize: 100,
      density: 'medium',
    },
  });
  

  async function onSubmit(data: z.infer<typeof Svg3dSchema>) {
    if (!user) {
        toast({ variant: 'destructive', title: 'Login Required', description: 'You must be logged in to create artwork.' });
        return;
    }
    setIsLoading(true);
    setError(null);

    try {
      const result = await generateSvg3dAction({
          ...data,
          creatorId: user.uid,
          creatorName: user.displayName || 'Anonymous Soul',
          creatorAvatarUrl: user.photoURL || undefined,
      });

      if (result.error) {
        setError(result.error);
      } else if (result.success && result.creation) {
        // The server action now returns the creation, which will be picked up by the listener
        toast({ title: 'Creation Added!', description: 'Your vision has been added to the gallery.'});
        form.reset({ ...form.getValues(), prompt: '' }); // Reset prompt but keep other settings
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'An unexpected error occurred.';
      setError(`Generation failed: ${message}`);
    }

    setIsLoading(false);
  }

  if (!user) {
    return (
        <main className="container mx-auto flex min-h-[80vh] items-center justify-center px-4">
            <Card className="w-full max-w-md text-center shadow-lg">
                <CardHeader>
                    <CardTitle>Enter the Community Gallery</CardTitle>
                    <CardDescription>Log in to view and contribute to the gallery.</CardDescription>
                </CardHeader>
                <CardContent>
                    <Button asChild>
                    <Link href="/login">
                        <LogIn className="mr-2 h-4 w-4" /> Login to Continue
                    </Link>
                    </Button>
                </CardContent>
            </Card>
        </main>
    );
  }

  return (
    <main className="container mx-auto max-w-6xl py-8">
       <div className="text-center mb-8">
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-primary flex items-center justify-center gap-3 font-headline">
          <GalleryHorizontal className="w-10 h-10" /> Community Gallery
        </h1>
        <p className="text-lg text-muted-foreground mt-2">A collective space to channel and display creative sparks.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        <div className="lg:col-span-1 space-y-8">
            <Card className="shadow-lg">
                <CardHeader>
                <CardTitle>Channel a New Creation</CardTitle>
                <CardDescription>
                    Enter a prompt and add your vision to the gallery for all to witness.
                </CardDescription>
                </CardHeader>
                <CardContent>
                <Form {...form}>
                    <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                    <FormField
                        control={form.control}
                        name="prompt"
                        render={({ field }) => (
                        <FormItem>
                            <FormLabel>Your Vision</FormLabel>
                            <FormControl>
                            <Input placeholder="e.g., 'The birth of a star'" {...field} />
                            </FormControl>
                            <FormMessage />
                        </FormItem>
                        )}
                    />
                    <div className="grid grid-cols-2 gap-4">
                        <FormField
                            control={form.control}
                            name="cubeSize"
                            render={({ field }) => ( <FormItem> <FormLabel>Cube Size</FormLabel> <FormControl> <Input type="number" {...field} /> </FormControl> <FormMessage /> </FormItem> )}
                        />
                        <FormField
                            control={form.control}
                            name="density"
                            render={({ field }) => ( <FormItem> <FormLabel>Density</FormLabel> <Select onValueChange={field.onChange} defaultValue={field.value}> <FormControl> <SelectTrigger> <SelectValue placeholder="Select density" /> </SelectTrigger> </FormControl> <SelectContent> <SelectItem value="low">Low</SelectItem> <SelectItem value="medium">Medium</SelectItem> <SelectItem value="high">High</SelectItem> </SelectContent> </Select> <FormMessage /> </FormItem> )}
                        />
                    </div>
                    <Button type="submit" disabled={isLoading} className="w-full">
                        {isLoading ? <><LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> Channeling...</> : <><Sparkles className="mr-2 h-4 w-4" /> Create</> }
                    </Button>
                    </form>
                </Form>
                </CardContent>
            </Card>
            
            {activeCreation && <SaveToTreasuryForm creation={activeCreation} />}
        </div>
        
        <div className="lg:col-span-2 space-y-8">
             <Card className="shadow-lg">
                <CardHeader>
                    {activeCreation && (
                         <div className="flex items-center gap-3">
                             <Avatar>
                                <AvatarImage src={activeCreation.creatorAvatarUrl || `https://i.pravatar.cc/150?u=${activeCreation.creatorId}`} />
                                <AvatarFallback>{activeCreation.creatorName.charAt(0)}</AvatarFallback>
                            </Avatar>
                            <div>
                                <CardTitle className="text-xl">{activeCreation.prompt}</CardTitle>
                                <CardDescription>
                                    Created by {activeCreation.creatorName} {activeCreation.createdAt && formatDistanceToNow(new Date(activeCreation.createdAt.seconds * 1000), { addSuffix: true })}
                                </CardDescription>
                            </div>
                        </div>
                    )}
                </CardHeader>
                <CardContent className="p-2 aspect-square">
                     <div className="w-full h-full bg-muted rounded-md">
                        {isLoading || isCreationsLoading ? (
                            <div className="flex w-full h-full justify-center items-center p-8"> <LoaderCircle className="w-12 h-12 animate-spin text-primary" /> </div>
                        ) : error ? (
                            <div className="flex w-full h-full justify-center items-center p-4"> <Alert variant="destructive"> <AlertTitle>Generation Failed</AlertTitle> <AlertDescription>{error}</AlertDescription> </Alert> </div>
                        ) : activeCreation ? (
                            <Svg3dCube pixels={activeCreation.pixels} />
                        ) : (
                             <div className="flex w-full h-full flex-col gap-4 justify-center items-center text-center text-muted-foreground p-4"> <Svg3dCube pixels={[]} className="w-16 h-16" /> <p>The collective creation will appear here.</p> </div>
                        )}
                    </div>
                </CardContent>
            </Card>

            <Card className="shadow-lg">
                <CardHeader>
                    <CardTitle>Gallery Feed</CardTitle>
                    <CardDescription>Browse all creations from the community.</CardDescription>
                </CardHeader>
                <CardContent>
                     {isCreationsLoading && <div className="flex justify-center p-4"><LoaderCircle className="w-8 h-8 animate-spin text-primary" /></div>}
                     {creationsError && <p className="text-destructive text-center">Error loading gallery: {creationsError.message}</p>}
                     <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
                        {creations?.map(creation => (
                            <button key={creation.id} onClick={() => setActiveCreation(creation)} className="relative aspect-square block border-2 border-transparent focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary rounded-lg overflow-hidden group">
                                <div className="w-full h-full bg-muted">
                                  <Svg3dCube pixels={creation.pixels} />
                                </div>
                                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center p-2 text-center text-white">
                                    <p className="text-xs font-bold line-clamp-2">{creation.prompt}</p>
                                    <p className="text-xs opacity-80">by {creation.creatorName}</p>
                                </div>
                                 {activeCreation?.id === creation.id && (
                                    <div className="absolute inset-0 border-4 border-primary rounded-md pointer-events-none" />
                                )}
                            </button>
                        ))}
                     </div>
                </CardContent>
            </Card>
        </div>

      </div>
    </main>
  );
}
