// src/app/wiki/svg3d/page.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Svg3dCube } from "@/components/icons/svg3d-cube";
import { ArrowLeft, Download, Beaker } from "lucide-react";
import Link from 'next/link';

const examplePixels = [
    { x: -20, y: 20, z: 10, color: "#FF5733" },
    { x: 15, y: -10, z: -15, color: "#33FF57" },
    { x: 5, y: 5, z: 25, color: "#3357FF" },
];

const objExample = `# 3D Point Cloud generated by Pleasance
v -20.0000 20.0000 10.0000 1.0000 0.3412 0.2000
v 15.0000 -10.0000 -15.0000 0.2000 1.0000 0.3412
v 5.0000 5.0000 25.0000 0.2000 0.3412 1.0000
`;

export default function Svg3dGuidePage() {
  return (
    <main className="container mx-auto min-h-screen max-w-4xl py-8 px-4 sm:px-6 lg:px-8">
        <div className="mb-6">
            <Button asChild variant="ghost">
                <Link href="/wiki">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Wiki
                </Link>
            </Button>
        </div>

      <div className="text-center mb-12">
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-primary flex items-center justify-center gap-3 font-headline">
          <Svg3dCube className="w-10 h-10" /> A Guide to SVG3D
        </h1>
        <p className="text-lg text-muted-foreground mt-2">Understanding the Art and Science of 3D Point-Cloud Generation.</p>
      </div>

      <div className="space-y-8">
        <Card>
            <CardHeader>
                <CardTitle>What is SVG3D?</CardTitle>
                <CardDescription>From a prompt to a constellation of pixels.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <p>In the context of our republic, "SVG3D" is the name we give to the generative art created in the Community Gallery. It's a <strong>3D point-cloud</strong>, a collection of colored points in a three-dimensional space, rendered within a Scalable Vector Graphic (SVG).</p>
                <p>Think of it as a digital sculpture made of light. Each point has an X, Y, and Z coordinate, along with a color. When you provide a prompt to the AI, it doesn't just create a flat image; it imagines a 3D structure and represents it as this cloud of pixels. The interactive viewer then allows you to rotate and explore this structure in real-time.</p>
            </CardContent>
        </Card>
        
        <Card>
            <CardHeader>
                <CardTitle>The Generation Process</CardTitle>
                <CardDescription>How the AI translates your vision.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <p>When you submit a prompt in the gallery, you're providing the AI with a conceptual seed. The AI uses this seed to determine the shape, color palette, and arrangement of the pixels. The parameters you control have a direct impact:</p>
                <ul className="list-disc pl-5 space-y-2">
                    <li><strong>Prompt:</strong> The most critical input. Concepts like "a lonely star" might produce a sparse, bright cloud, while "a dense nebula" would create a thick, colorful cluster.</li>
                    <li><strong>Cube Size:</strong> This defines the conceptual boundary of the 3D space. While all points are mapped to a -50 to 50 range internally, this parameter can influence the perceived scale in the AI's generation.</li>
                    <li><strong>Density:</strong> This controls the number of points in the cloud. Low density is sparse (~300-500 points), while High density is rich and detailed (~2000-3000 points).</li>
                </ul>
                 <div className="flex justify-center p-4">
                    <Button asChild>
                        <Link href="/svg3d">
                            <Beaker className="mr-2 h-4 w-4" />
                            Try it in the Personal Workshop
                        </Link>
                    </Button>
                </div>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle>The .obj File Format</CardTitle>
                <CardDescription>The blueprint for physical creation.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <p>When you download your creation, you receive a <code>.obj</code> file. This is a standard 3D geometry definition file format. For our point clouds, the format is simple. Each line starts with a 'v', followed by the X, Y, and Z coordinates, and then the R, G, and B values for the color (normalized from 0 to 1).</p>
                <pre className="p-4 bg-muted rounded-md text-xs overflow-x-auto"><code>{objExample}</code></pre>
                <p>This file is the digital blueprint that can be read by 3D fabrication software, bridging the gap between your virtual creation and a physical object.</p>
                 <div className="flex justify-center p-4">
                    <Button variant="secondary" disabled>
                        <Download className="mr-2 h-4 w-4" />
                        Example .obj File
                    </Button>
                </div>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle>From Virtual to Physical</CardTitle>
                <CardDescription>Manifesting your creation in the real world.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <p>The true power of this tool is realized when you manifest your creation. After saving your SVG3D artwork to your Treasury, you can submit it to the <strong>Workshop of Manifestation</strong>. The <code>.obj</code> file you generated is the key.</p>
                <p>A network of artisans (like NNO.Studio for 3D printing) can use this file to create a physical representation of your digital sculpture. This is the final step in the journey from a simple idea to a tangible asset, a testament to the creative power of the republic.</p>
            </CardContent>
        </Card>

      </div>
    </main>
  );
}
